name: Terraform Pipeline
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: Init
        working-directory: RDS
        run: |
          terraform init 

      - name: Apply
        working-directory: RDS
        run:
          terraform apply -auto-approve